In [ ]:
# introduction to numpy
# 1D & 2D
# Manipulation 
'''    
    - reshape
    - arithemetic operation with sacalar
    - accessing row , column , elements 
    - reversing , slicing
    - with functions like mean, max, min
    - size and dimension

'''

In [3]:
import numpy as np

In [ ]:
# 1D array

([1,2,3,4,5])

# 2D array 
([[1,2,3],[4,5,6]]) 

([[1,2,3],[4,5,6],[7,8,9]])

([[1,2,3],
  [4,5,6],
  [7,8,9]])

In [4]:
#   1D array
array1 = np.array([1,2,3,4,5])

print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# reshaping array 1

array2 = array1.reshape(5,1)

print(array2)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:


# 2D array 

array3 = np.array([[1,2,3,4,5],[2,4,6,8,10]])

print(array3)
print(array3.shape)
print(array3[0]) # first row in this array3
print(array3[0][0])
print(array3[0,0])  # another way of [0][0]
print(array3[1][1])
print('')
print('array3 reshaped to ')
print(array3.shape)
print('')
array3 = array3.reshape(5,2)
print(array3)

print('')
print(array3[0]) # first row in reshaped array3
print(array3[-1]) # print final row 
print(array3[0][0]) # first element in first row 
print(array3[-1][0]) 

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
(2, 5)
[1 2 3 4 5]
1
1
4

array3 reshaped to 
(2, 5)

[[ 1  2]
 [ 3  4]
 [ 5  2]
 [ 4  6]
 [ 8 10]]

[1 2]
[ 8 10]
1
8


In [ ]:
# 1D array manipulaiton

In [6]:
array4 = np.array([1,2,3,4,5,6,7,8])
print(array4.shape)

(8,)


In [7]:
print(array4 + 10) # 10 added for every element 
print(array4 * 2)
print(array4 - 3)
print(array4 / 2)

print("")
array5 = np.array([4,9,16,25,36])
print(np.sqrt(array5))

[11 12 13 14 15 16 17 18]
[ 2  4  6  8 10 12 14 16]
[-2 -1  0  1  2  3  4  5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]

[2. 3. 4. 5. 6.]


In [8]:
# useful functions

print(array5.sum())
print(array5.mean())
print(array5.max())
print(array5.min())

90
18.0
36
4


In [ ]:
# array attributes
#  size , dimension, datatype, itemsize

print(array5)
print(array5.size)
print(array5.ndim)
print(array5.dtype) #.  int64 refers to a 64-bit signed integer data type.
print(array5.itemsize)
print("")
print(array4)

[ 4  9 16 25 36]
5
1
int64
8

[1 2 3 4 5 6 7 8]


In [11]:
array6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array6.size)
print(array6.ndim)

9
2


In [19]:
# vectorized operaitons

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [26]:
# functions 

arr = np.array([1,2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [57]:
# slicing of array

arr9 = np.array([1,2,3,4,5,6,7,8,9])
arr8 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr9[0:0])
print(arr9[0:1])
print(arr9[1:3])
print(arr9[2:6])
print(arr9[2:6])
print("")
print(arr8[1:, 1:])
print(arr8[0:, :2])
print(arr8[0:, 0:3])

[]
[1]
[2 3]
[3 4 5 6]
[3 4 5 6]

[[6 7 8]]
[[1 2]
 [5 6]]
[[1 2 3]
 [5 6 7]]


In [62]:
# modidying elements

arr8[0,0] = 100
print(arr8)

arr8[0,1] = 99
print(arr8)

[[100   2   3   4]
 [  5   6   7   8]]
[[100  99   3   4]
 [  5   6   7   8]]


In [ ]:
# statistical operations and normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
print(mean)
std = np.std(data)
print(std)

normalized_data = (data - mean) /std
print(normalized_data)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [71]:
arr77 = np.array([1,2,3,4,5,6,7,8])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

3.5
3.5
1.707825127659933
2.9166666666666665


In [73]:
#  logical operation 

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
