In [1]:
import numpy as np

### Creating array

In [3]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
arr = np.array([1,2,3,4], dtype=float) # float or 'f4' -> short for float
print(arr)
arr =np.array([1,2,3,4], dtype=bool)
print(arr)
arr =np.array([1,2,3,4], dtype=np.int32)
print(arr)

[1. 2. 3. 4.]
[ True  True  True  True]
[1 2 3 4]


In [15]:
arr =np.array([0,1,0,1], dtype=bool)
arr1 =np.array([0,0,1,1], dtype=bool)
#  0 ->. flase , 1 -> true
print(arr)
print(arr1)

[False  True False  True]
[False False  True  True]


arange

In [20]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

arr = np.arange(1, 13)
print(arr)

arr = np.arange(5, 20)
print(arr)

# for arange (x, y) -> in created array , [x, x+1, x+2, ....., y-1]
# y will not included in array


[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


reshape 

In [28]:
#  if original array has M elements , then we can reshape to (a, b, c, ...), only if :
#  M = a x b x c ...

arr = np.array([1,2,3,4,5,6]) # 6 elements  -> 3x2 or 2x3  -> row , column
mat = arr.reshape(3, 2) 
print(mat)

print()
mat1 = arr.reshape(2, 3)
print(mat1)

print()
arr = np.array([1,2,3,4,5,6,7,8,9]) # 9 elements -> so 3x3 or 1x9 or 9x1
mat = arr.reshape(3, 3)
print(mat)

mat = arr.reshape(1, 9)
print(mat)


mat = arr.reshape(9, 1)
print(mat)


mat = arr.reshape(9,) # normal list
print(mat) 

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# possibily of reshaping , example: if 5 elements : (5,)  (5, 1)   (1, 5)

#  same like this for all prime number : 2,3,5,7,11,13,17,19,23....
# because we know for prime numbers: example for 7 : only divisible by 1 and 7

In [36]:
#  ones and zeros

tst = np.ones((2, 3))
print(tst)

print()
tst = np.ones((3, 2))
print(tst)

print()
tst = np.zeros((2, 3))
print(tst)


#  np.ones() and np.zeros() Are Useful for Initializing Weights, Masks, Padding, etc.
#  because : Both functions create arrays filled with a single constant value, which is extremely useful in ML, DL, and data processing.

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# random


# np.random.seed(0)          # for reproducible results
# without seed : different every run
# Because random numbers are different each time unless you lock the seed.



In [46]:
# without random

np.random.rand(3) # generates different values for each time i run this shell

array([0.19806286, 0.76053071, 0.16911084])

In [50]:
# with seed

np.random.seed(10)

np.random.rand(3) # for each time i run this shell , the value will be same

array([[0.74880388, 0.49850701, 0.22479665]])

In [54]:
rand = np.random.rand(1,3)
randint = np.random.randint(10, 50, (2, 3)) # random int

print('rand:\n', rand)
print('randint:\n', randint)

# for rand -----
# Always floats (decimal values)
# Range: 0.0 ≤ value < 1.0
# use case : Model weights init, probabilities, noise

# for randint -----
# Always integers
# Range: 10 ≤ value < 50
# use case: Sampling, IDs, categorical values, testing

rand:
 [[0.82608225 0.10540183 0.28357668]]
randint:
 [[37 28 39]
 [23 32 33]]


### Linearly spaced array (np.linspace())

In [59]:
arr = np.linspace(0, 1, 5)
print(arr)


# here it output will be : 5 equally spaced values from 0 to 1 inclusive. with 4 intervals

#   np.linspace(x, y, z)
# from  x to y equally spaced values, with z number of values , z-1 intervals

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Formula to calculate the equal difference btw the numbers

#  Formula = (end - start) / (num_points - 1)

'''
example here : np.linspace(0, 1, 5)

start = 0
end = 1
num_points = 5


step = (end - start) / (num_points - 1)
     = (1 - 0) / (5 - 1)
     = 1 / 4
     = 0.25

'''

In [58]:
arr = np.linspace(1, 10, 4)
print(arr)

# the difference:
# (10-1)/(4-1)
# 9/3 = 3

[ 1.  4.  7. 10.]


In [62]:
# identity matrix - diagonel elements = 1

i = np.eye(3)
print(i)

print()
k = np.eye(4)
print(k)

#  Used a lot in linear algebra and ML 
# eg : regularization

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Numpy array attributes

In [66]:
arr = np.arange(1,11).reshape(5, 2)
print(arr)

print()
arr = np.arange(1,7).reshape(3, 2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[1 2]
 [3 4]
 [5 6]]


In [79]:
# number of dimensions
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3]])
arr2 = np.array([[[1,2,3]]])

arr3 = np.array([[1,2,3],
                [4,5,6]]) # 2 row and 3 column



print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print()
print(arr.shape)
print(arr1.shape)
print(arr2.shape)
print()
print(arr3.shape)



1
2
3

(3,)
(1, 3)
(1, 1, 3)

(2, 3)
(1, 3, 3)


In [80]:
arr4 = np.array([
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                 ])  

print(arr4.shape)


'''

Level 1 → [   ...   ] : 1 block (depth)
Level 2 → [ [ ... ], [ ... ], [ ... ] ] : rows inside
Level 3 → [1, 2, 3] : columns

'''

or 

'''

(1, 3, 3)
 ↑  ↑  ↑
 |  |  |
 |  |  └ columns (3)
 |  └ rows (3)
 └ number of 2D matrices (1)

'''

(1, 3, 3)


In [82]:
arr5 = np.array([
                [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]
               ])

print(arr5.shape)


arr6 = np.array([
                [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]],

                 [[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]]
               ])

print(arr6.shape)

(2, 3, 3)
(3, 3, 3)


In [86]:
# size : total number of elements

print(arr4)
print()
print(f'number of elements in arr4 : {arr4.size}')

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

number of elements in arr4 : 9


In [87]:
print(arr6.size)

27


In [97]:
# data type of elements (dtype)

print(arr.dtype)
print(arr4.dtype)



int64
int64


In [99]:
# change data type while creating array

arr10 = np.array([
                [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                ], dtype=float)

print(arr10)                
print(arr10.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


In [100]:
# changing data type of already existing array

arr4 = np.array([
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                 ])  

# changing data type 

datatype = arr4.astype(float)
print(datatype)

print()
print(datatype.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]

float64


In [110]:
# item size

'''

int32	4 bytes	4
float32	4 bytes	4
float64	8 bytes	8
int64	8 bytes	8

'''


print(arr4.itemsize) 
type32 = arr4.astype(np.int32)
type555 = arr4.astype('float32')

print(type32.itemsize)
print(type555.itemsize)

8
4
4


In [112]:
# nbytes

print(arr4.nbytes)  # nbytes -> total memory 
print(arr4.size)    # size -> total elements

72
9


In [117]:
# type and conversions

arr_float = np.array([1.1, 2.1, 4.6])
print('originial:', arr_float, arr_float.dtype)

arr_int = arr_float.astype(int)
print('converted:', arr_int, arr_int.dtype)

originial: [1.1 2.1 4.6] float64
converted: [1 2 4] int64


### Array & Scalar operation

In [118]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [126]:
print(a + 10)
print(a - 10)
print(a * 2)
print(a ** 2)
print(a / 2)

# Vector (element-wise) Operations

print(b + 5)
print(a + b)
print(a * b)


[11 12 13]
[-9 -8 -7]
[2 4 6]
[1 4 9]
[0.5 1.  1.5]
[ 9 10 11]
[5 7 9]
[ 4 10 18]


In [128]:
# Dot product

dot = np.dot(a, b)

print(dot)

32


In [131]:
# array functions

c = np.array([1, 2, 3, 4, 5])
print(c)


# min / max / sum / prod
print('min:', c.min())
print('max:', c.max())
print('sum:', c.sum())
print('prod:', c.prod())

[1 2 3 4 5]
min: 1
max: 5
sum: 15
prod: 120


In [136]:
# mean / median / std / var

print('mean:', c.mean())
print('median:', np.median(c))
print('std:', c.std())
print('var:', c.var())

mean: 3.0
median: 3.0
std: 1.4142135623730951
var: 2.0


In [162]:
#  round, floor, ceil

x = np.array([1.2, 1.8, -1.2, -1.8])
print(x)

print()
# round : rounding number to nearest integer
print(np.round(x))
# floor : rounds down to nearest smaller integer
print(np.floor(x))
# ceil : always rounds up to the nearest higher integer

[ 1.2  1.8 -1.2 -1.8]

[ 1.  2. -1. -2.]
[ 1.  1. -2. -2.]


In [ ]:
'''
| Function | Action          | `1.2` | `1.5` | `1.8` | `2.5`               |
| -------- | --------------- | ----- | ----- | ----- | ------------------- |
| `round`  | nearest integer | 1     | 2     | 2     | 2 (banker rounding) |
| `floor`  | always go down  | 1     | 1     | 1     | 2                   |
| `ceil`   | always go up    | 2     | 2     | 2     | 3                   |


'''

In [149]:
# Trigonometric functions

angles = np.array([0, np.pi/2])
print(angles)
print('sin:', np.round(np.sin(angles)))
print('cos:', np.round(np.cos(angles)))
print('tan:', np.round(np.tan(angles)))

[0.         1.57079633]
sin: [0. 1.]
cos: [1. 0.]
tan: [0.00000000e+00 1.63312394e+16]


In [153]:
# Log and exponential function

vals = np.array([1, np.e])

print('log:', np.round(np.log(vals), 3))
print('exp:', np.round(np.exp(np.array([0, 1])), 3))

log: [0. 1.]
exp: [1.    2.718]


In [171]:
# Indexing & Slicing

# 1D indexing and slicing : 

arr = np.array([10, 20, 30, 40, 50, 60])
print("arr:", arr)

print()
print('arr[1:4]:', arr[1:4]) # index 1,2,3 : 20,30,40
print('arr[1:5]:', arr[1:5])
print('arr[:4]:', arr[:5]) # index 0 to 4
print('arr[-3:]:', arr[-3:]) # last 3 elements
print('arr[::-4]:', arr[::-1])  # reverse

arr: [10 20 30 40 50 60]

arr[1:4]: [20 30 40]
arr[1:5]: [20 30 40 50]
arr[:4]: [10 20 30 40 50]
arr[-3:]: [40 50 60]
arr[::-4]: [60 50 40 30 20 10]


In [182]:
# 2D indexing

m = np.arange(1, 13).reshape(3, 4)
print('m:\n', m)

print()
print('element m[1, 2]:', m[1, 2])  # indexing of element :  row : 0, 1 then column : 0, 1, 2 :  so element == 7
print('element m[2,3]:', m[2, 3])

print()
print('row m[1]:', m[1])
print('row m[1]:', m[2])

print()
print('column m[:, 1]:', m[:, 1])
print('column m[:, 2]:', m[:, 2])

m:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

element m[1, 2]: 7
element m[2,3]: 12

row m[1]: [5 6 7 8]
row m[1]: [ 9 10 11 12]

column m[:, 1]: [ 2  6 10]
column m[:, 2]: [ 3  7 11]


In [186]:
# combined slicing

print(m)

sub = m[0:2, 1:3]  # row : 0-1 and column : 1-2
print(sub)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


### Iteration on numpy array

In [191]:
arr = np.array([10, 20, 30, 40, 50, 60])

for x in arr:
    print(x)

print()
for x in arr:
    if x % 20 ==0 :
        print(x)

10
20
30
40
50
60

20
40
60


In [197]:
# 2D iteration

m = np.arange(1, 13).reshape(3, 4)
print(m)
print()

print('row-wise')
for row in m:
    print(row)

print('\nElement-wise:')
for row in m:
    for val in row:
        print(val, end='')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

row-wise
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

Element-wise:
123456789101112

### reshaping, transpose, ravel

In [202]:


# reshaping : changing the shape(dimension) of the array without changing the data
arr = np.arange(1, 7)
print(arr)

print()
reshaped = arr.reshape(2, 3)
print(reshaped)


#  here 6 elements → can reshape into (2×3), (3×2), (6,1), (1,6)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [212]:
# transpose : Swap rows and columns (flip the matrix)
m = np.array([[1, 2, 3],[4, 5, 6]])
n = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(m)

print()
print(m.T)
print()
print(n.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [215]:
#  ravel : Flatten the array into 1D (one dimension)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ravel())

[1 2 3 4 5 6]


In [216]:
arr = np.arange(1, 9)
print("Original:", arr)

reshaped = arr.reshape(2, 4)
print("\nReshaped (2x4):\n", reshaped)

transposed = reshaped.T
print("\nTransposed:\n", transposed)

raveled = reshaped.ravel()
print("\nRaveled:", raveled)

Original: [1 2 3 4 5 6 7 8]

Reshaped (2x4):
 [[1 2 3 4]
 [5 6 7 8]]

Transposed:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]

Raveled: [1 2 3 4 5 6 7 8]


In [ ]:
# summary of reshaping, transpose, ravel

'''
| Operation        | What It Does              | Example Input | Example Output |
| ---------------- | ------------------------- | ------------- | -------------- |
| `reshape`        | Changes shape, keeps data | `(6,)`        | `(2,3)`        |
| `transpose (.T)` | Swaps rows & columns      | `(2,3)`       | `(3,2)`        |
| `ravel`          | Flattens to 1D            | `(2,3)`       | `(6,)`         |

'''

### Stacking

### with 1D

In [220]:
# vstack : Stack arrays on top of each other (row-wise)         v → vertical → downwards
# hstack : Stack side by side (column-wise)                     h → horizontal → rightwards


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# vstack
v = np.vstack((a, b))
# Arrays become rows one below another
# Shapes must match in columns


# hstack
h = np.hstack((a, b))
# Adds arrays next to each other
# Result stays 1D if inputs are 1D

print("vstack:\n", v)
print("\nhstack:\n", h)

vstack:
 [[1 2 3]
 [4 5 6]]

hstack:
 [1 2 3 4 5 6]


### with 2D

In [221]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [222]:
np.vstack((A, B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [223]:
np.hstack((A, B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Splitting
### vertical splitting - vsplit , horizontal splitting - hsplit

In [238]:
# vsplit - split by rows
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

print(m)
print()
print('vertically splitting by rows')
v1, v2, v3= np.vsplit(m, 3)
print('v1:\n',v1)
print('v2:\n',v2)
print('v3:\n',v3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

vertically splitting by rows
v1:
 [[1 2 3 4]]
v2:
 [[5 6 7 8]]
v3:
 [[ 9 10 11 12]]


In [246]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12],
              [13,14,15,16]])

v1, v2 = np.vsplit(m, 2)
print('v1 with first 2 row:\n',v1)
print()
print('v2 with last 2 row:\n',v2)


v1 with first 2 row:
 [[1 2 3 4]
 [5 6 7 8]]

v2 with last 2 row:
 [[ 9 10 11 12]
 [13 14 15 16]]


In [255]:
#  manually splitting, Using indices

m = np.array([[1, 2, 3, 4],    # 0
              [5, 6, 7, 8],    # 1
              [9,10,11,12],])  # 2

# splitting the row with index 2 
v1, v2 = np.vsplit(m, [2])
print(v1)
print()
print(v2)

print('splitting the row with index 1')
# splitting the row with index 1
v1, v2 = np.vsplit(m, [1])
print()
print('v1 with single row:\n',v1)
print()
print('v2 with last 2 row:\n',v2)




[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]]
splitting the row with index 1

v1 with single row:
 [[1 2 3 4]]

v2 with last 2 row:
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [256]:
# Using array_split :  allow uneven split

m = np.array([[1, 2, 3, 4],    # 0
              [5, 6, 7, 8],    # 1
              [9,10,11,12],])  # 2


v1, v2 = np.array_split(m, 2)  # array_split adjusts automatically
print(v1)
print(v2)


[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]


### Horizontal splitting - hsplit 

In [259]:
# splitting columns (left ↔ right)

m = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

# (3, 4) → 3 rows, 4 columns
h1, h2 = np.hsplit(m, 2)
print('h1:\n',h1)
print()
print('h2:\n',h2)

h1:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]

h2:
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [261]:
# Using Indices (Cut at Specific Column)

h1, h2 = np.hsplit(m, [1])
print(h1)
print()
print(h2)

[[1]
 [5]
 [9]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [265]:
h1, h2, h3 = np.hsplit(m, [1, 3])
print('h1:\n',h1)
print()
print('h2:\n',h2)
print()
print('h3:\n',h3)

h1:
 [[1]
 [5]
 [9]]

h2:
 [[ 2  3]
 [ 6  7]
 [10 11]]

h3:
 [[ 4]
 [ 8]
 [12]]


In [272]:
# To Allow Uneven Splits → Use array_split
print(m)
h1, h2, h3 = np.array_split(m, 3, axis=1)
print()
print(h1)
print()
print(h2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 3]
 [ 7]
 [11]]


In [273]:
m = np.arange(1, 13).reshape(3, 4)
print("m:\n", m)

hs = np.hsplit(m, 2)
vs = np.vsplit(m, 3)

print("\nHorizontal split (2 parts):")
for part in hs:
    print(part, "\n")

print("Vertical split (3 parts):")
for part in vs:
    print(part, "\n")

m:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontal split (2 parts):
[[ 1  2]
 [ 5  6]
 [ 9 10]] 

[[ 3  4]
 [ 7  8]
 [11 12]] 

Vertical split (3 parts):
[[1 2 3 4]] 

[[5 6 7 8]] 

[[ 9 10 11 12]] 

