In [1]:
import numpy as np

### Creating array

In [3]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
arr = np.array([1,2,3,4], dtype=float) # float or 'f4' -> short for float
print(arr)
arr =np.array([1,2,3,4], dtype=bool)
print(arr)
arr =np.array([1,2,3,4], dtype=np.int32)
print(arr)

[1. 2. 3. 4.]
[ True  True  True  True]
[1 2 3 4]


In [15]:
arr =np.array([0,1,0,1], dtype=bool)
arr1 =np.array([0,0,1,1], dtype=bool)
#  0 ->. flase , 1 -> true
print(arr)
print(arr1)

[False  True False  True]
[False False  True  True]


arange

In [20]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

arr = np.arange(1, 13)
print(arr)

arr = np.arange(5, 20)
print(arr)

# for arange (x, y) -> in created array , [x, x+1, x+2, ....., y-1]
# y will not included in array


[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


reshape 

In [28]:
#  if original array has M elements , then we can reshape to (a, b, c, ...), only if :
#  M = a x b x c ...

arr = np.array([1,2,3,4,5,6]) # 6 elements  -> 3x2 or 2x3  -> row , column
mat = arr.reshape(3, 2) 
print(mat)

print()
mat1 = arr.reshape(2, 3)
print(mat1)

print()
arr = np.array([1,2,3,4,5,6,7,8,9]) # 9 elements -> so 3x3 or 1x9 or 9x1
mat = arr.reshape(3, 3)
print(mat)

mat = arr.reshape(1, 9)
print(mat)


mat = arr.reshape(9, 1)
print(mat)


mat = arr.reshape(9,) # normal list
print(mat) 

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# possibily of reshaping , example: if 5 elements : (5,)  (5, 1)   (1, 5)

#  same like this for all prime number : 2,3,5,7,11,13,17,19,23....
# because we know for prime numbers: example for 7 : only divisible by 1 and 7

In [36]:
#  ones and zeros

tst = np.ones((2, 3))
print(tst)

print()
tst = np.ones((3, 2))
print(tst)

print()
tst = np.zeros((2, 3))
print(tst)


#  np.ones() and np.zeros() Are Useful for Initializing Weights, Masks, Padding, etc.
#  because : Both functions create arrays filled with a single constant value, which is extremely useful in ML, DL, and data processing.

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# random


# np.random.seed(0)          # for reproducible results
# without seed : different every run
# Because random numbers are different each time unless you lock the seed.



In [46]:
# without random

np.random.rand(3) # generates different values for each time i run this shell

array([0.19806286, 0.76053071, 0.16911084])

In [50]:
# with seed

np.random.seed(10)

np.random.rand(3) # for each time i run this shell , the value will be same

array([[0.74880388, 0.49850701, 0.22479665]])

In [54]:
rand = np.random.rand(1,3)
randint = np.random.randint(10, 50, (2, 3)) # random int

print('rand:\n', rand)
print('randint:\n', randint)

# for rand -----
# Always floats (decimal values)
# Range: 0.0 ≤ value < 1.0
# use case : Model weights init, probabilities, noise

# for randint -----
# Always integers
# Range: 10 ≤ value < 50
# use case: Sampling, IDs, categorical values, testing

rand:
 [[0.82608225 0.10540183 0.28357668]]
randint:
 [[37 28 39]
 [23 32 33]]


### Linearly spaced array (np.linspace())

In [59]:
arr = np.linspace(0, 1, 5)
print(arr)


# here it output will be : 5 equally spaced values from 0 to 1 inclusive. with 4 intervals

#   np.linspace(x, y, z)
# from  x to y equally spaced values, with z number of values , z-1 intervals

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Formula to calculate the equal difference btw the numbers

#  Formula = (end - start) / (num_points - 1)

'''
example here : np.linspace(0, 1, 5)

start = 0
end = 1
num_points = 5


step = (end - start) / (num_points - 1)
     = (1 - 0) / (5 - 1)
     = 1 / 4
     = 0.25

'''

In [58]:
arr = np.linspace(1, 10, 4)
print(arr)

# the difference:
# (10-1)/(4-1)
# 9/3 = 3

[ 1.  4.  7. 10.]


In [62]:
# identity matrix - diagonel elements = 1

i = np.eye(3)
print(i)

print()
k = np.eye(4)
print(k)

#  Used a lot in linear algebra and ML 
# eg : regularization

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Numpy array attributes

In [66]:
arr = np.arange(1,11).reshape(5, 2)
print(arr)

print()
arr = np.arange(1,7).reshape(3, 2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[[1 2]
 [3 4]
 [5 6]]


In [79]:
# number of dimensions
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3]])
arr2 = np.array([[[1,2,3]]])

arr3 = np.array([[1,2,3],
                [4,5,6]]) # 2 row and 3 column



print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print()
print(arr.shape)
print(arr1.shape)
print(arr2.shape)
print()
print(arr3.shape)



1
2
3

(3,)
(1, 3)
(1, 1, 3)

(2, 3)
(1, 3, 3)


In [80]:
arr4 = np.array([
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                 ])  

print(arr4.shape)


'''

Level 1 → [   ...   ] : 1 block (depth)
Level 2 → [ [ ... ], [ ... ], [ ... ] ] : rows inside
Level 3 → [1, 2, 3] : columns

'''

or 

'''

(1, 3, 3)
 ↑  ↑  ↑
 |  |  |
 |  |  └ columns (3)
 |  └ rows (3)
 └ number of 2D matrices (1)

'''

(1, 3, 3)


In [82]:
arr5 = np.array([
                [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]
               ])

print(arr5.shape)


arr6 = np.array([
                [[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]],

                 [[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]]
               ])

print(arr6.shape)

(2, 3, 3)
(3, 3, 3)


In [86]:
# size : total number of elements

print(arr4)
print()
print(f'number of elements in arr4 : {arr4.size}')

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

number of elements in arr4 : 9


In [87]:
print(arr6.size)

27


In [97]:
# data type of elements (dtype)

print(arr.dtype)
print(arr4.dtype)



int64
int64


In [99]:
# change data type while creating array

arr10 = np.array([
                [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                ], dtype=float)

print(arr10)                
print(arr10.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


In [ ]:
# changing data type of already existing array

arr4 = np.array([
                 [[1,2,3],
                 [4,5,6],
                 [7,8,9]]
                 ])  

# changing data type 

datatype = arr4.astype(float)
print(datatype)

print()
print(datatype.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]

float64


In [110]:
# item size

'''

int32	4 bytes	4
float32	4 bytes	4
float64	8 bytes	8
int64	8 bytes	8

'''


print(arr4.itemsize) 
type32 = arr4.astype(np.int32)
type555 = arr4.astype('float32')

print(type32.itemsize)
print(type555.itemsize)

8
4
4


In [ ]:
# nbytes

print(arr4.nbytes)  # nbytes -> total memory 
print(arr4.size)    # size -> total elements

72
9


In [ ]:
# next is 3.0 ---------  Type & Conversions – astype()