In [1]:
import numpy as np

### Creating array

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4], dtype=float) # float or 'f4' -> short for float
print(arr)
arr =np.array([1,2,3,4], dtype=bool)
print(arr)
arr =np.array([1,2,3,4], dtype=np.int32)
print(arr)

[1. 2. 3. 4.]
[ True  True  True  True]
[1 2 3 4]


In [ ]:
arr =np.array([0,1,0,1], dtype=bool)
arr1 =np.array([0,0,1,1], dtype=bool)
#  0 ->. flase , 1 -> true
print(arr)
print(arr1)

[False  True False  True]
[False False  True  True]


arange

In [20]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

arr = np.arange(1, 13)
print(arr)

arr = np.arange(5, 20)
print(arr)

# for arange (x, y) -> in created array , [x, x+1, x+2, ....., y-1]
# y will not included in array


[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


reshape 

In [ ]:
#  if original array has M elements , then we can reshape to (a, b, c, ...), only if :
#  M = a x b x c ...

arr = np.array([1,2,3,4,5,6]) # 6 elements  -> 3x2 or 2x3  -> row , column
mat = arr.reshape(3, 2) 
print(mat)

print()
mat1 = arr.reshape(2, 3)
print(mat1)

print()
arr = np.array([1,2,3,4,5,6,7,8,9]) # 9 elements -> so 3x3 or 1x9 or 9x1
mat = arr.reshape(3, 3)
print(mat)

mat = arr.reshape(1, 9)
print(mat)


mat = arr.reshape(9, 1)
print(mat)


mat = arr.reshape(9,) # normal list
print(mat) 

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# possibily of reshaping , example: if 5 elements : (5,)  (5, 1)   (1, 5)

#  same like this for all prime number : 2,3,5,7,11,13,17,19,23....
# because we know for prime numbers: example for 7 : only divisible by 1 and 7

In [ ]:
#  ones and zeros

tst = np.ones((2, 3))
print(tst)

print()
tst = np.ones((3, 2))
print(tst)

print()
tst = np.zeros((2, 3))
print(tst)


#  np.ones() and np.zeros() Are Useful for Initializing Weights, Masks, Padding, etc.
#  because : Both functions create arrays filled with a single constant value, which is extremely useful in ML, DL, and data processing.

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# random


# np.random.seed(0)          # for reproducible results
# without seed : different every run
# Because random numbers are different each time unless you lock the seed.



In [ ]:
# without random

np.random.rand(3) # generates different values for each time i run this shell

array([0.19806286, 0.76053071, 0.16911084])

In [ ]:
# with seed

np.random.seed(10)

np.random.rand(3) # for each time i run this shell , the value will be same

array([[0.74880388, 0.49850701, 0.22479665]])

In [53]:
rand = np.random.rand(1,3)
randint = np.random.randint(10, 50, (2, 3)) # random int

print('rand:\n', rand)
print('randint:\n', randint)

rand:
 [[0.72743551 0.54088093 0.13145815]]
randint:
 [[35 23 38]
 [32 40 40]]
