### Data Encoding
- nominal & ordinal 
- onehot
- label



In [ ]:
# what is encoding : 
# process of converting categorical data into numeric form so that machine learning algorithm can process it


# types of categorical data:
# nomial - categorical with no order.   example: color, city, gender
# ordinal - categorical with meaningful order. example : low < medium < high

In [ ]:
# use in ml :
# Data encoding enables machine learning models to understand, process, and learn from categorical data correctly and efficiently.

## Label encoding

- It assigns an integer (0, 1, 2, …) to each unique category.
- Label encoding is based on alphebetical order , first  0 , then 1 , .....

In [1]:

import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [13]:
df = pd.DataFrame({
    'color':('red','green','blue','red','blue','blue','green')
})
df

color
0    red
1  green
2   blue
3    red
4   blue
5   blue
6  green

In [14]:
encoded_colors = encoder.fit_transform(df)
encoded_colors

/Users/thameem/Desktop/thameem/Data Analysis/.env/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0, 2, 0, 0, 1])

In [15]:
y = ["Pass", "Fail", "Pass", "Fail", "Pass"]


In [18]:
y_encoded = encoder.fit_transform(y)

print(y_encoded)
print(encoder.classes_)

[1 0 1 0 1]
['Fail' 'Pass']


In [24]:
# fit

y1 = ["Yes", "No", "Yes", "No"]
k1 = encoder.fit(y1)
# it internally learn, but does not change the data


In [ ]:
# transform
y1_encoded = k1.transform(y)
print(y1_encoded)
# uses already-learned information to convert data.
# here k1 is  data that already internally learned using fit(y)

[1 0 1 0]


In [ ]:
# fit_transform
y1 = ["Yes", "No", "Yes", "No"]
encoder.fit_transform(y1)
# it changes the data
# fit_transform(y) = fit(y) + transform(y)

array([1, 0, 1, 0])

fit() learns parameters from data, transform() applies them, and fit_transform() performs both in one step.

### Ordinal encoding

In [29]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [30]:
df = pd.DataFrame({
    'size':['small', 'large', 'medium', 'large', 'medium', 'small']
})

In [31]:

enc = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [32]:
enc.fit_transform(df[["size"]])

array([[0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [35]:
enc.transform([['small']])

/Users/thameem/Desktop/thameem/Data Analysis/.env/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [36]:
enc.transform([['large']])

/Users/thameem/Desktop/thameem/Data Analysis/.env/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

### Target guided ordinal encoding

### One hot encoding

In [ ]:
# converts a categorical feature into multiple binary(0/1) columns, one column per catefory

# Only one column is “hot” (1) for each row, others are 0.

# Why One-Hot Encoding is Needed: Label Encoding creates fake order for nominal data.

In [ ]:
'''
Red → 0
Blue → 1
Green → 2
'''
# and it may think 
# Green > Blue > Red 
# so that why we use onehot encoding

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
encode = OneHotEncoder()

In [26]:
color = ["Red", "Blue", "Green", "Red"] # (4,)
# What OneHotEncoder Expects : (number_of_samples, number_of_features)
# that means : (rows, columns) , for us : (4 sample,  1 color)
# it expects (4,1) 
colors = np.array(["Red", "Blue", "Green", "Red"]).reshape(-1,1)
# reshape(-1,1) : here -1 means : Automatically calculate this dimension for me , so 4 row 
# so this transforms to like this :
# reshape(-1, 1) = reshape(4, 1)
'''
[['Red']
 ['Blue']
 ['Green']
 ['Red']]
 '''

"\n[['Red']\n ['Blue']\n ['Green']\n ['Red']]\n "

In [22]:
ohe = OneHotEncoder(sparse_output=False)

In [23]:
encoded_colors = ohe.fit_transform(colors)

print(encoded_colors)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
